import type { Listing, Market } from "./types";

/**
 * PREVIEW RECORDS ONLY.
 *
 * Every record here has `origin: "preview"` and MUST be rendered with a visible
 * "Preview listing" label. These illustrate how Gnome works — they are not real
 * inventory and must never be presented as available near a visitor.
 */

const hoursAgo = (h: number): string => new Date(Date.now() - h * 3_600_000).toISOString();
const daysFromNow = (d: number): string => new Date(Date.now() + d * 86_400_000).toISOString();

export const PREVIEW_MARKETS: Market[] = [
  {
    id: "mkt-preview-1",
    ownerId: "usr-preview-1",
    origin: "preview",
    name: "Sycamore Street Garden",
    slug: "sycamore-street-garden",
    tagline: "Two raised beds and more tomatoes than we can eat.",
    description:
      "We started with one bed in 2019 and got carried away. Most weeks there's a surplus of tomatoes, basil, and whatever the zucchini decides to do. Porch pickup is easiest — I'll send the details once we sort out a time.",
    emblem: "🍅",
    location: { label: "Richmond Heights, OH", zip: "44143", approxMiles: 1.2 },
    pickupPreference: "porch",
    published: true,
    plan: "grower",
    growingSince: "2019",
    completedExchanges: 84,
    responseHours: 3,
    createdAt: hoursAgo(9000),
    updatedAt: hoursAgo(30),
  },
  {
    id: "mkt-preview-2",
    ownerId: "usr-preview-2",
    origin: "preview",
    name: "The Hen House on Elm",
    slug: "hen-house-on-elm",
    tagline: "Six hens, one very opinionated rooster.",
    description:
      "Backyard flock, pasture-raised, eggs collected the same morning. Cartons returned get you fifty cents off. Please check your local rules on egg sales — I follow Ohio's small-flock exemption.",
    emblem: "🥚",
    location: { label: "Lyndhurst, OH", zip: "44124", approxMiles: 2.8 },
    pickupPreference: "porch",
    published: true,
    plan: "grower",
    growingSince: "2021",
    completedExchanges: 213,
    responseHours: 1,
    createdAt: hoursAgo(7000),
    updatedAt: hoursAgo(6),
  },
  {
    id: "mkt-preview-3",
    ownerId: "usr-preview-3",
    origin: "preview",
    name: "Little Creek Farm Stand",
    slug: "little-creek-farm-stand",
    tagline: "Four acres, market stand open Saturdays.",
    description:
      "A small family operation running since 1994. We grow greens, root vegetables, and cut flowers, and we sell at two regional markets. Gnome is where we list midweek surplus so it doesn't go to the compost pile.",
    emblem: "🌾",
    location: { label: "Chesterland, OH", zip: "44026", approxMiles: 6.4 },
    pickupPreference: "at-market",
    published: true,
    plan: "farm",
    growingSince: "1994",
    completedExchanges: 641,
    responseHours: 5,
    createdAt: hoursAgo(20000),
    updatedAt: hoursAgo(52),
  },
  {
    id: "mkt-preview-4",
    ownerId: "usr-preview-4",
    origin: "preview",
    name: "Balcony Botanicals",
    slug: "balcony-botanicals",
    tagline: "Herbs and seedlings from a third-floor balcony.",
    description:
      "Proof you don't need land. Everything here comes out of about forty square feet of containers. I start way too many seedlings every spring and pass the extras along.",
    emblem: "🌿",
    location: { label: "Cleveland Heights, OH", zip: "44118", approxMiles: 4.1 },
    pickupPreference: "meet-public",
    published: true,
    plan: "neighbor",
    growingSince: "2022",
    completedExchanges: 27,
    responseHours: 8,
    createdAt: hoursAgo(4000),
    updatedAt: hoursAgo(14),
  },
];

export const PREVIEW_LISTINGS: Listing[] = [
  {
    id: "lst-preview-1",
    origin: "preview",
    marketId: "mkt-preview-1",
    type: "free",
    status: "active",
    title: "Way too many cherry tomatoes",
    description:
      "The Sungolds went feral. Bring a bag or a container and take as much as you want — I pick fresh every morning and there's more coming all week.",
    category: "vegetables",
    photo: "🍅",
    quantity: 8,
    unit: "pints",
    priceCents: null,
    location: { label: "Richmond Heights, OH", zip: "44143", approxMiles: 1.2 },
    availability: "All week, mornings are best",
    pickupPreference: "porch",
    privatePickupNote: "Cooler on the side porch — I'll share the house number once we confirm.",
    featured: false,
    createdAt: hoursAgo(5),
    expiresAt: daysFromNow(5),
  },
  {
    id: "lst-preview-2",
    origin: "preview",
    marketId: "mkt-preview-2",
    type: "sale",
    status: "active",
    title: "Farm eggs, collected this morning",
    description:
      "Dozen mixed brown and blue-green eggs from six hens. Unwashed and uncracked, kept cool. Bring back a clean carton and the next dozen is fifty cents off.",
    category: "eggs",
    photo: "🥚",
    quantity: 4,
    unit: "dozen",
    priceCents: 600,
    location: { label: "Lyndhurst, OH", zip: "44124", approxMiles: 2.8 },
    availability: "Restocked most mornings",
    pickupPreference: "porch",
    privatePickupNote: "Egg fridge in the garage, code shared after we confirm.",
    featured: true,
    createdAt: hoursAgo(11),
    expiresAt: daysFromNow(3),
  },
  {
    id: "lst-preview-3",
    origin: "preview",
    marketId: "mkt-preview-4",
    type: "trade",
    status: "active",
    title: "Basil and mint starts — looking for peppers",
    description:
      "Twelve healthy starts in 3-inch pots, hardened off and ready to go in the ground. I'd love to swap for pepper seedlings, any variety, or honestly a jar of something you canned.",
    category: "seedlings",
    photo: "🌿",
    quantity: 12,
    unit: "starts",
    priceCents: null,
    tradeFor: "Pepper seedlings, or anything you've canned",
    location: { label: "Cleveland Heights, OH", zip: "44118", approxMiles: 4.1 },
    availability: "Next two weekends",
    pickupPreference: "meet-public",
    privatePickupNote: "Usually meet at the library parking lot on Lee Road.",
    featured: false,
    createdAt: hoursAgo(28),
    expiresAt: daysFromNow(10),
  },
  {
    id: "lst-preview-4",
    origin: "preview",
    marketId: "mkt-preview-3",
    type: "sale",
    status: "active",
    title: "Rainbow chard, cut to order",
    description:
      "Big glossy bunches, stems in every color. We cut the morning of pickup so it's still cold when you get it. Great for sautéing or tossing into soup.",
    category: "vegetables",
    photo: "🥬",
    quantity: 20,
    unit: "bunches",
    priceCents: 350,
    location: { label: "Chesterland, OH", zip: "44026", approxMiles: 6.4 },
    availability: "Saturday market, 8am–1pm",
    pickupPreference: "at-market",
    privatePickupNote: "Stand 14 at the Chesterland Saturday market.",
    featured: false,
    createdAt: hoursAgo(50),
    expiresAt: daysFromNow(6),
  },
  {
    id: "lst-preview-5",
    origin: "preview",
    marketId: "mkt-preview-1",
    type: "wanted",
    status: "active",
    title: "Looking for extra canning jars",
    description:
      "Quart or pint wide-mouth, rings included if you have them. Happy to pay, trade tomatoes, or both. I'm putting up sauce over the next few weeks and keep running short.",
    category: "tools",
    photo: "🫙",
    quantity: 24,
    unit: "jars",
    priceCents: null,
    location: { label: "Richmond Heights, OH", zip: "44143", approxMiles: 1.2 },
    availability: "Anytime through the fall",
    pickupPreference: "arrange",
    privatePickupNote: "Happy to drive to you within about ten miles.",
    featured: false,
    createdAt: hoursAgo(72),
    expiresAt: daysFromNow(20),
  },
  {
    id: "lst-preview-6",
    origin: "preview",
    marketId: "mkt-preview-3",
    type: "sale",
    status: "active",
    title: "Zinnia bouquets, cut fresh",
    description:
      "Mixed-color bunches of about fifteen stems, wrapped in kraft paper. They last a good week if you change the water. Cut the morning you pick them up.",
    category: "flowers",
    photo: "💐",
    quantity: 10,
    unit: "bouquets",
    priceCents: 800,
    location: { label: "Chesterland, OH", zip: "44026", approxMiles: 6.4 },
    availability: "Through first frost",
    pickupPreference: "at-market",
    privatePickupNote: "Stand 14 at the Chesterland Saturday market.",
    featured: true,
    createdAt: hoursAgo(90),
    expiresAt: daysFromNow(12),
  },
  {
    id: "lst-preview-7",
    origin: "preview",
    marketId: "mkt-preview-4",
    type: "free",
    status: "active",
    title: "Finished compost, bring a bucket",
    description:
      "Two years of kitchen scraps and leaves, screened and ready. Dark and crumbly. Take as much as you can carry, I just need the bin space back.",
    category: "compost",
    photo: "🪴",
    quantity: 6,
    unit: "buckets",
    priceCents: null,
    location: { label: "Cleveland Heights, OH", zip: "44118", approxMiles: 4.1 },
    availability: "This weekend",
    pickupPreference: "arrange",
    privatePickupNote: "Side gate, I'll leave it unlocked once we pick a time.",
    featured: false,
    createdAt: hoursAgo(120),
    expiresAt: daysFromNow(4),
  },
  {
    id: "lst-preview-8",
    origin: "preview",
    marketId: "mkt-preview-2",
    type: "trade",
    status: "active",
    title: "Sourdough loaf for garden produce",
    description:
      "I bake two loaves every Saturday and can only eat one. Naturally leavened, baked that morning. Trade me anything you grew — greens, squash, herbs, surprise me.",
    category: "other",
    photo: "🍞",
    quantity: 1,
    unit: "loaf per week",
    priceCents: null,
    tradeFor: "Anything from your garden",
    location: { label: "Lyndhurst, OH", zip: "44124", approxMiles: 2.8 },
    availability: "Saturdays",
    pickupPreference: "porch",
    privatePickupNote: "Porch pickup after 10am Saturday.",
    featured: false,
    createdAt: hoursAgo(140),
    expiresAt: daysFromNow(8),
  },
  {
    id: "lst-preview-9",
    origin: "preview",
    marketId: "mkt-preview-1",
    type: "sale",
    status: "completed",
    title: "Pickling cucumbers, last of the season",
    description: "The final picking went to a neighbor who's making a big batch of half-sours.",
    category: "vegetables",
    photo: "🥒",
    quantity: 0,
    unit: "lbs",
    priceCents: 250,
    location: { label: "Richmond Heights, OH", zip: "44143", approxMiles: 1.2 },
    availability: "Sold out",
    pickupPreference: "porch",
    privatePickupNote: "",
    featured: false,
    createdAt: hoursAgo(400),
    expiresAt: daysFromNow(-2),
  },
];
